camel.jbang.dependencies=camel-openai,camel-docling

camel.component.openai.apiKey={{env:OPENAI_API_KEY}}
camel.component.openai.baseUrl={{env:OPENAI_BASE_URL}}
camel.component.openai.model={{env:OPENAI_MODEL}}

# Docling Serve
camel.component.docling.useDoclingServe=true
camel.component.docling.doclingServeUrl=http://localhost:5001

# for single console stream
camel.main.durationMaxIdleSeconds=5
