camel.jbang.dependencies=camel:openai,com.h2database:h2:2.2.224,org.apache.commons:commons-dbcp2:2.9.0

# for single console stream
camel.main.durationMaxMessages=2

## OpenAI
camel.component.openai.apiKey={{env:OPENAI_API_KEY}}
camel.component.openai.baseUrl={{env:OPENAI_BASE_URL}}
camel.component.openai.model={{env:OPENAI_MODEL}}

# Database (H2 In-Memory)
camel.datasource.url=jdbc:h2:mem:inventorydb;DB_CLOSE_DELAY=-1
camel.datasource.driver-class-name=org.h2.Driver
camel.datasource.username=sa
camel.datasource.password=

# MyBatis Config
camel.component.mybatis.configuration-uri=SqlMapConfig.xml
