camel.jbang.dependencies=camel:openai,org.postgresql:postgresql:42.7.2,org.apache.commons:commons-dbcp2:2.9.0

# for single console stream
camel.main.durationMaxMessages=1

## OpenAI
camel.component.openai.apiKey={{env:OPENAI_API_KEY}}
camel.component.openai.baseUrl={{env:OPENAI_BASE_URL}}
camel.component.openai.model={{env:OPENAI_MODEL}}

# MyBatis Config
camel.component.mybatis.configuration-uri=SqlMapConfig.xml
